spring:
  flyway:
    enabled: false
  sql:
    init:
      mode: always
      schema-locations:
        - classpath*:/schemas/oracle/V1-dataflow.sql
        - classpath*:/schemas/oracle/V1-skipper.sql
        - classpath*:/schemas/oracle/V2-dataflow.sql
        - classpath*:/schemas/oracle/V2-dataflow-after.sql
        - classpath*:/schemas/oracle/V3-dataflow.sql
        - classpath*:/schemas/oracle/V4-dataflow.sql
        - classpath*:/schemas/oracle/V5-dataflow.sql
        - classpath*:/schemas/oracle/V6-dataflow.sql
        - classpath*:/schemas/oracle/V7-dataflow.sql
        - classpath*:/schemas/oracle/V8-dataflow.sql
        - classpath*:/schemas/oracle/V9-dataflow.sql
        - classpath*:/schemas/oracle/V10-dataflow.sql
