spring:
  flyway:
    enabled: false
  sql:
    init:
      mode: always
      schema-locations:
        - classpath*:/schemas/sqlserver/V1-dataflow.sql
        - classpath*:/schemas/sqlserver/V1-skipper.sql
        - classpath*:/schemas/sqlserver/V2-dataflow.sql
        - classpath*:/schemas/sqlserver/V2-dataflow-after.sql
        - classpath*:/schemas/sqlserver/V3-dataflow.sql
        - classpath*:/schemas/sqlserver/V4-dataflow.sql
        - classpath*:/schemas/sqlserver/V4_1-dataflow.sql
        - classpath*:/schemas/sqlserver/V5-dataflow.sql
        - classpath*:/schemas/sqlserver/V6-dataflow.sql
        - classpath*:/schemas/sqlserver/V7-dataflow.sql
        - classpath*:/schemas/sqlserver/V8-dataflow.sql
        - classpath*:/schemas/sqlserver/V9-dataflow.sql
        - classpath*:/schemas/sqlserver/V10-dataflow.sql
