spring:
  flyway:
    enabled: false
  sql:
    init:
      mode: always
      schema-locations:
        - classpath*:/schemas/postgresql/V1-dataflow.sql
        - classpath*:/schemas/postgresql/V1-skipper.sql
        - classpath*:/schemas/postgresql/V2-dataflow.sql
        - classpath*:/schemas/postgresql/V2-dataflow-after.sql
        - classpath*:/schemas/postgresql/V3-dataflow.sql
        - classpath*:/schemas/postgresql/V4-dataflow.sql
        - classpath*:/schemas/postgresql/V5-dataflow.sql
        - classpath*:/schemas/postgresql/V6-dataflow.sql
        - classpath*:/schemas/postgresql/V7-dataflow.sql
        - classpath*:/schemas/postgresql/V8-dataflow.sql
        - classpath*:/schemas/postgresql/V9-dataflow.sql
        - classpath*:/schemas/postgresql/V10-dataflow.sql
        - classpath*:/schemas/postgresql/V11-dataflow.sql
