apiVersion: apps/v1
kind: Deployment
metadata:
  name: skipper
  labels:
    app: skipper
spec:
  selector:
    matchLabels:
      app: skipper
  replicas: 1
  template:
    metadata:
      labels:
        app: skipper
    spec:
      containers:
      - name: skipper
        image: springcloud/spring-cloud-skipper-server:2.11.3
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: config
            mountPath: /workspace/config
            readOnly: true
          - name: database
            mountPath: /etc/secrets/database
            readOnly: true
        ports:
        - containerPort: 7577
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 7577
          initialDelaySeconds: 1
          periodSeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 7577
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 2
        startupProbe:
          tcpSocket:
            port: 7577
          initialDelaySeconds: 30
          periodSeconds: 3
          failureThreshold: 20
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 1.0
            memory: 1024Mi
          requests:
            cpu: 0.5
            memory: 640Mi
        env:
          - name: LANG
            value: en_US.utf8
          - name: LC_ALL
            value: en_US.utf8
          - name: JDK_JAVA_OPTIONS
            value: '-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8'
          - name: SPRING_CLOUD_CONFIG_ENABLED
            value: 'false'
          - name: SPRING_CLOUD_KUBERNETES_CONFIG_ENABLE_API
            value: 'false'
          - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
            value: 'false'
          - name: SPRING_CLOUD_KUBERNETES_SECRETS_PATHS
            value: /etc/secrets
      serviceAccountName: scdf-sa
      volumes:
        - name: config
          configMap:
            name: skipper
            items:
            - key: application.yaml
              path: application.yaml
        - name: database
          secret:
            secretName: mariadb
