info:
  app:
    name: "@project.artifactId@"
    version: "@project.version@"
server:
  port: 7577
spring:
  main:
    banner-mode: "off"
  data:
    rest:
      base-path: /api
  cloud:
    skipper:
      server:
        packageRepositories:
          -
            name: experimental
            url: http://skipper-repository.cfapps.io/repository/experimental
            description: Experimental Skipper Repository
            repoOrder: 0
          -
            name: local
            url: http://${spring.cloud.client.hostname}:7577
            local: true
            description: Default local database backed repository
            repoOrder: 1


maven:
  remoteRepositories:
    springRepo:
      url: https://repo.spring.io/libs-snapshot




logging:
  level:
    org.springframework.beans: 'WARN'
    org.springframework.context: 'WARN'
    org.springframework.core.io: 'WARN'
    org.springframework.data: 'WARN'
    org.springframework.jmx: 'WARN'
    org.springframework.web: 'WARN'
    org.springframework.security: 'WARN'
    org.springframework.integration: 'WARN'
    org.springframework.boot: 'WARN'
    org.hibernate: 'WARN'
    # The following INFO is to log the generated password when using basic security
    org.springframework.boot.autoconfigure.security: 'INFO'
    org.springframework.skipper: 'INFO'