redis:
  image: redis

timesource:
  image: springcloud/dataflow-app-launcher
  links:
    - redis
  ports:
    - "8080:8080"
  environment:
    SPRING_REDIS_HOST: redis
    MODULES: org.springframework.cloud.stream.module:time-source:1.0.0.BUILD-SNAPSHOT
    SPRING_CLOUD_STREAM_BINDINGS_OUTPUT: ticktock

logsink:
  image: springcloud/dataflow-app-launcher
  links:
    - redis
  ports:
    - "8081:8080"
  environment:
    SPRING_REDIS_HOST: redis
    MODULES: org.springframework.cloud.stream.module:log-sink:1.0.0.BUILD-SNAPSHOT
    SPRING_CLOUD_STREAM_BINDINGS_INPUT: ticktock
