#@data/values
---
scdf:
  deploy:
    database:
      type: mariadb
  server:
    image:
      tag: 2.10.4-SNAPSHOT
    service:
      type:
        NodePort
  skipper:
    image:
      tag: 2.9.4-SNAPSHOT
  ctr:
    image:
      tag: 2.10.4-SNAPSHOT
