version: '3'

services:

  mysql:
    entrypoint: ["echo", "MySQL service is disabled"]

  postgres:
    image: postgres:10
    container_name: dataflow-postgres
    restart: always
    environment:
      POSTGRES_DB: dataflow
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpw
    expose:
      - 5432
    ports:
      - 5432:5432

  dataflow-server:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dataflow
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpw
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
    entrypoint: "./wait-for-it.sh -t 240 postgres:5432 -- java -jar /maven/spring-cloud-dataflow-server.jar"

  skipper-server:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dataflow
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpw
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
    entrypoint: "./wait-for-it.sh -t 240 postgres:5432 -- java -Djava.security.egd=file:/dev/./urandom -jar /spring-cloud-skipper-server.jar"

