version: '3'

# Reconfigures the default docker-compose.yml to replace MySQL by Postgres
# Usage: docker-compose -f ./docker-compose.yml -f ./docker-compose-postgres.yml up
services:

  mysql:
    entrypoint: ["echo", "MySQL service is disabled"]

  postgres:
    image: postgres:10
    container_name: dataflow-postgres
    restart: always
    environment:
      POSTGRES_DB: dataflow
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpw
    expose:
      - 5432
    ports:
      - 5432:5432

  dataflow-server:
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/dataflow
      - spring.datasource.username=root
      - spring.datasource.password=rootpw
      - spring.datasource.driver-class-name=org.postgresql.Driver
    entrypoint: "./wait-for-it.sh -t 240 postgres:5432 -- java -jar /maven/spring-cloud-dataflow-server.jar"

  skipper-server:
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/dataflow
      - spring.datasource.username=root
      - spring.datasource.password=rootpw
      - spring.datasource.driver-class-name=org.postgresql.Driver
    entrypoint: "./wait-for-it.sh -t 240 postgres:5432 -- java -jar /maven/spring-cloud-skipper-server.jar"

