scdf-type:
  oss:
    release: '2.10.3'
    snapshot: '2.11.0-SNAPSHOT'
    ga-snapshot: '2.10.4-SNAPSHOT'
  pro:
    release: '1.5.3'
    snapshot: '1.6.0-SNAPSHOT'
    ga-snapshot: '1.5.4-SNAPSHOT'
default:
  scdf-type: 'oss'
  version: 'snapshot'
