apiVersion: v1
kind: ConfigMap
metadata:
  name: scdf-server
  labels:
    app: scdf-server
data:
  application-kubernetes.yaml: |-
    logging:
      level:
        root: info
        org.springframework: debug
    management:
      defaults:
        metrics:
          export:
            enabled: false
    spring:
      output:
        ansi:
          enabled: NEVER
      cloud:
        deployer:
          kubernetes:
            imagePullPolicy: IfNotPresent
            imagePullSecret: registry-key
        dataflow:
          metrics.dashboard:
            url: 'http://localhost:3000'
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    imagePullPolicy: IfNotPresent
                    imagePullSecret: registry-key
                    limits:
                      memory: 1024Mi

#      metrics:
#        export:
#          prometheus:
#            enabled: true
#            rsocket:
#              enabled: true
#              host: prometheus-proxy
#              port: 7001
