---
apiVersion: v1
kind: Secret
metadata:
  name: scdf-datasource
  labels:
    app: scdf-datasource
# same values as in src/kubernetes/postgtresql/postgresql-secrets.yaml
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXMtcm9vdA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scdf-datasource
data:
  SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgresql:5432/dataflow'
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: 'org.postgresql.Driver'
  SPRING_DATASOURCE_TEST_ON_BORROW: 'true'
  SPRING_DATASOURCE_VALIDATION_QUERY: "SELECT 1"
  SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_USE_UNICODE: 'true'
  SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_CHARACTER_ENCODING: 'UTF-8'
