apiVersion: v1
kind: ConfigMap
metadata:
  name: skipper
  labels:
    app: skipper
data:
  application-kubernetes.yaml: |-
    logging:
      level:
        root: info
        org.springframework: debug
        io.fabric8: debug
    spring:
      output:
        ansi:
          enabled: NEVER
      cloud:
        deployer:
          kubernetes:
            imagePullPolicy: IfNotPresent
            imagePullSecret:
              -name: registry-key
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:
                    imagePullPolicy: IfNotPresent
                    imagePullSecret:
                      - name: registry-key
                    environmentVariables: 'JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=-1,LANG=en_US.utf8,LC_ALL=en_US.utf8,JDK_JAVA_OPTIONS=-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8,SPRING_CLOUD_CONFIG_ENABLED=false,SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka-broker:9092,SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=${KAFKA_ZK_SERVICE_HOST}:${KAFKA_ZK_SERVICE_PORT}'
                    request:
                      memory: 1024Mi
                      cpu: 1500m
                    readinessProbeDelay: 1
                    readinessProbeTimeout: 5
                    livenessProbeDelay: 1
                    livenessProbeTimeout: 2
                    startupProbeDelay: 20
                    startupProbeTimeout: 5
                    startupProbeFailure: 50
    management:
      defaults:
        metrics:
          export:
            enabled: false
