datasources:
  - name: 'ScdfPrometheus'
    type: 'prometheus'
    access: 'proxy'
    org_id: 1
    url: 'https://prometheus:9090'
    is_default: true
    version: 5
    editable: true
    read_only: false
