version: '3.3'
services:

  # Grafana uses the InfluxDB datasource
  influxdb:
    image: influxdb:1.7.5
    container_name: 'influxdb'
    ports:
      - '8086:8086'

  # Grafana SCDF InfluxdDB pre-built image
  grafana:
    image: springcloud/spring-cloud-dataflow-grafana-influxdb:${DATAFLOW_VERSION:?DATAFLOW_VERSION is not set! Use 'export DATAFLOW_VERSION=local-server-image-tag'}
    container_name: 'grafana'
    ports:
      - '3000:3000'
