apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-rsocket-proxy
  labels:
    app: prometheus-rsocket-proxy
spec:
#  replicas: 3
  selector:
    matchLabels:
      app: prometheus-rsocket-proxy
  template:
    metadata:
      labels:
        app: prometheus-rsocket-proxy
    spec:
      serviceAccountName: prometheus-rsocket-proxy
      containers:
        - name: prometheus-rsocket-proxy
          image: micrometermetrics/prometheus-rsocket-proxy:2.0.0-M2
          imagePullPolicy: IfNotPresent
          ports:
            - name: scrape
              containerPort: 8080
            - name: rsocket
              containerPort: 7001
          resources:
            requests:
              cpu: 1500m
              memory: 1Gi
          env:
            - name: LOGGING_LEVEL_IO_MICROMETER
              value: DEBUG
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
