#@data/values-schema
---
#! all scdf options
scdf:
  registry:
    secret:
      #! if defined ref will be added as imagePullSecrets resources
      ref: ""
  deploy:
    binder:
      #! if binder deployment is enabled
      enabled: true
      type: rabbit
      rabbit:
        image:
          repository: rabbitmq
          tag: 3.9.5
          digest: ""
        #! rabbit username (defaults to dataflow)
        username: ZGF0YWZsb3c=
        #! rabbit password (default to secret)
        password: c2VjcmV0
        #@schema/type any=True
        config:
      kafka:
        brokerImage:
          repository: confluentinc/cp-kafka
          tag: 5.5.2
          digest: ""
        zkImage:
          repository: confluentinc/cp-zookeeper
          tag: 5.5.2
          digest: ""
    #! deploy database settings
    database:
      #! if database deployment is enabled
      enabled: true
      #! database type, either mariadb or postgres (required)
      type: postgres
      postgres:
        #! database username (defaults to dataflow)
        username: ZGF0YWZsb3c=
        #! database password (default to secret)
        password: c2VjcmV0
        image:
          repository: postgres
          tag: "10"
          digest: ""
      mariadb:
        #! database username (defaults to dataflow)
        username: ZGF0YWZsb3c=
        #! database password (default to secret)
        password: c2VjcmV0
        image:
          repository: mariadb
          tag: "10.4"
          digest: ""
  server:
    image:
      #! dataflow server image repository id
      repository: springcloud/spring-cloud-dataflow-server
      #! dataflow server image tag (required)
      tag: ""
      digest: ""
    service:
      type: ClusterIP
    resources:
      limits:
        cpu: 1000m
        memory: 2048Mi
      requests:
        cpu: 500m
        memory: 1024Mi
    metrics:
      dashboard:
        url: ""
    contextPath: ""
    database:
      url: ""
      username: ""
      password: ""
      driverClassName: ""
      testOnBorrow: true
      validationQuery: ""
    #! additional dataflow server configuration
    #@schema/type any=True
    config:
  ctr:
    image:
      #! ctr image repository id
      repository: springcloud/spring-cloud-dataflow-composed-task-runner
      #! ctr image tag (required)
      tag: ""
      digest: ""
  skipper:
    image:
      #! skipper server image repository id
      repository: springcloud/spring-cloud-skipper-server
      #! skipper server image tag (required)
      tag: ""
      digest: ""
    service:
      type: ClusterIP
    resources:
      limits:
        cpu: 1000m
        memory: 2048Mi
      requests:
        cpu: 500m
        memory: 1024Mi
    database:
      url: ""
      username: ""
      password: ""
      driverClassName: ""
      testOnBorrow: true
      validationQuery: ""
    #! additional skipper server configuration
    #@schema/type any=True
    config:
  #! external binder settings, will disable binder deployment
  binder:
    kafka:
      broker:
        host: ""
        port: 9092
      zk:
        host: ""
        port: 9092
    rabbit:
      host: ""
      port: 5672
      username: ""
      password: ""
  #! optional feature
  feature:
    monitoring:
      prometheus:
        enabled: false
        image:
          repository: prom/prometheus
          tag: v2.12.0
          digest: ""
      grafana:
        enabled: false
        image:
          repository: springcloud/spring-cloud-dataflow-grafana-prometheus
          tag: ""
          digest: ""
        service:
          type: ClusterIP
      prometheusRsocketProxy:
        enabled: false
        image:
          repository: micrometermetrics/prometheus-rsocket-proxy
          tag: 1.0.0
          digest: ""
