name: CI Carvel

on:
  push:
    branches:
      - main
    paths:
      - 'src/carvel/**'
  workflow_dispatch:

jobs:

  # test templating before publishing a package
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - uses: carvel-dev/setup-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup npm
      shell: bash
      working-directory: src/carvel
      run: npm install
    - name: npm ci
      shell: bash
      working-directory: src/carvel
      run: npm ci
    - name: Lint
      shell: bash
      working-directory: src/carvel
      run: npm run format-check
    - name: Test
      shell: bash
      working-directory: src/carvel
      run: npm test
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.8.4
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Login dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Configure Env
      run: |
        echo SPRING_CLOUD_DATAFLOW_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV
        echo SPRING_CLOUD_SKIPPER_VERSION=$(mvn help:evaluate -Dexpression=spring-cloud-skipper.version  -pl spring-cloud-dataflow-parent -q -DforceStdout) >> $GITHUB_ENV
        echo SPRING_CLOUD_DATAFLOW_VERSION_NOPOSTFIX=$(echo '${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}' | mvn build-helper:parse-version help:evaluate -q -DforceStdout) >> $GITHUB_ENV

    # Builds a package bundle
    - name: Build Package Bundle
      id: build-package-bundle
      uses: ./.github/actions/build-package-bundle
      with:
        dataflow-version: '${{ env.SPRING_CLOUD_DATAFLOW_VERSION }}'
        skipper-version: '${{ env.SPRING_CLOUD_SKIPPER_VERSION }}'
        server-version: '${{ env.SPRING_CLOUD_DATAFLOW_VERSION }}'
        server-repository: 'springcloud/spring-cloud-dataflow-server'
        ctr-version: '${{ env.SPRING_CLOUD_DATAFLOW_VERSION }}'
        package-name: 'scdf'
        package-bundle-template: 'src/carvel/templates/bundle/package'
        imgpkg-lock-template: 'src/carvel/templates/imgpkg'
        config: 'src/carvel/config'

    # Publishes scdf package bundle as it needs to be in place
    # before repository bundle can be created.
    - name: Publish Package Bundle
      id: publish-package-bundle
      uses: ./.github/actions/publish-bundle
      with:
        path: '${{ steps.build-package-bundle.outputs.bundle-path }}'
        repository: 'springcloud/scdf-package'
        version: '${{ env.SPRING_CLOUD_DATAFLOW_VERSION_NOPOSTFIX }}'
        prerelease: 'SNAPSHOT'

    # Builds a repository bundle
    - name: Build Repository Bundle
      id: build-repository-bundle
      uses: ./.github/actions/build-repository-bundle
      with:
        version: '${{ env.SPRING_CLOUD_DATAFLOW_VERSION }}'
        repo-bundle-template: 'src/carvel/templates/bundle/repo'
        package-bundle-repository: 'springcloud/scdf-package'
        package-name: 'scdf'

    # Publishes scdf repo bundle
    - name: Publish Repository Bundle
      id: publish-repository-bundle
      uses: ./.github/actions/publish-bundle
      with:
        path: '${{ steps.build-repository-bundle.outputs.bundle-path }}'
        repository: 'springcloud/scdf-repo'
        version: '${{ env.SPRING_CLOUD_DATAFLOW_VERSION_NOPOSTFIX }}'
        prerelease: 'SNAPSHOT'
