name: CI Carvel

on:
  push:
    branches:
      - main
    paths:
      - 'src/carvel/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch or tag to use to determine version numbers'
      package_version:
        description: 'Package version to publish. If blank will match dataflow version'
        required: false

jobs:
  # test templating before publishing a package
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'
    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch && inputs.branch || github.ref }}
        path: 'target'
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - uses: carvel-dev/setup-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup npm
      shell: bash
      working-directory: src/carvel
      run: npm install
    - name: npm ci
      shell: bash
      working-directory: src/carvel
      run: npm ci
    - name: Lint
      shell: bash
      working-directory: src/carvel
      run: npm run format-check
    - name: Test
      shell: bash
      working-directory: src/carvel
      run: npm test
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.8.8
        maven-mirror: 'https://dlcdn.apache.org/maven/maven-3/'
    - name: Configure Env
      run: |
        pushd target
          source .github/workflows/export-app-versions.sh
          echo DATAFLOW_VERSION=$DATAFLOW_VERSION >> $GITHUB_ENV
          echo SKIPPER_VERSION=$SKIPPER_VERSION >> $GITHUB_ENV
          echo DATAFLOW_VERSION_NOPOSTFIX=$DATAFLOW_VERSION_NOPOSTFIX >> $GITHUB_ENV
          if [ "${{ inputs.package_version }}" != "" ]; then
            echo PACKAGE_VERSION=${{ inputs.package_version }} >> $GITHUB_ENV
          else
            echo PACKAGE_VERSION=$DATAFLOW_VERSION_NOPOSTFIX >> $GITHUB_ENV
          fi
        popd
    outputs:
      dataflow-version: '${{ env.DATAFLOW_VERSION }}'
      skipper-version: '${{ env.SKIPPER_VERSION }}'
      dataflow-version-no-postfix: '${{ env.DATAFLOW_VERSION_NOPOSTFIX }}'
      package-version: '${{ env.PACKAGE_VERSION }}'
  publish:
    needs:
      - prepare
    uses: ./.github/workflows/common-carvel.yml
    with:
      package-name: 'scdf'
      package-version: ${{ needs.prepare.outputs.package-version }}
      server-repository: 'springcloud/spring-cloud-dataflow-server'
      package-bundle: 'springcloud/scdf-oss-package'
      repository-bundle: 'springcloud/scdf-oss-repo'
      dataflow-version: ${{ needs.prepare.outputs.dataflow-version }}
      dataflow-version-no-postfix: ${{ needs.prepare.outputs.dataflow-version-no-postfix }}
      server-version: ${{ needs.prepare.outputs.dataflow-version }}
      ctr-version: ${{ needs.prepare.outputs.dataflow-version }}
      skipper-version: ${{ needs.prepare.outputs.skipper.version }}
      prerelease: 'SNAPSHOT'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
