name: common-carvel

on:
  workflow_call:
    inputs:
      package-name:
        type: string
        description: 'Package Name'
        required: true
      package-version:
        type: string
        description: 'Package Version'
        required: true
      package-bundle:
        type: string
        description: 'Package Bundle name'
        required: true
      repository-bundle:
        type: string
        description: 'Repository Bundle name'
        required: true
      dataflow-version:
        type: string
        description: 'Spring Cloud Data Flow Container Version'
        required: true
      server-version:
        type: string
        description: 'Server Version'
        required: true
      skipper-version:
        type: string
        description: 'Spring Cloud Skipper Container Version'
        required: true
      ctr-version:
        type: string
        description: 'Composed Task Runner Container Version'
        required: true
      server-repository:
        type: string
        description: 'Docker repo for Data Flow Server'
        required: true
      skipper-repository:
        type: string
        description: 'Docker repo for Skipper Server'
        required: true
    secrets:
      DOCKERHUB_USERNAME:
      DOCKERHUB_TOKEN:

jobs:
  # test templating before publishing a package
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Ensure scripts are executable
      shell: bash
      run: find . -type f -name "*.sh" -exec chmod a+x '{}' \;
    - uses: carvel-dev/setup-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Login dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # Builds a package bundle
    - name: Build Package Bundle
      id: build-package-bundle
      uses: ./.github/actions/build-package-bundle
      with:
        dataflow-version: ${{ inputs.dataflow-version }}
        skipper-version: ${{ inputs.skipper-version }}
        skipper-repository: ${{ inputs.skipper-repository }}
        server-version: ${{ inputs.server-version }}
        server-repository: ${{ inputs.server-repository }}
        ctr-version: ${{ inputs.ctr-version }}
        package-name: ${{ inputs.package-name }}
        package-bundle-template: 'src/carvel/templates/bundle/package'
        imgpkg-lock-template: 'src/carvel/templates/imgpkg'
        config: 'src/carvel/config'
        project-directory: '.'

    # Publishes scdf package bundle as it needs to be in place
    # before repository bundle can be created.
    - name: Publish Package Bundle
      id: publish-package-bundle
      uses: ./.github/actions/publish-bundle
      with:
        path: '${{ steps.build-package-bundle.outputs.bundle-path }}'
        repository: ${{ inputs.package-bundle }}
        version: ${{ inputs.package-version }}
        project-directory: '.'

    # Builds a repository bundle
    - name: Build Repository Bundle
      id: build-repository-bundle
      uses: ./.github/actions/build-repository-bundle
      with:
        version: ${{ inputs.package-version }}
        repo-bundle-template: 'src/carvel/templates/bundle/repo'
        package-bundle-repository: ${{ inputs.package-bundle }}
        package-name: ${{ inputs.package-name }}
        project-directory: '.'

    # Publishes scdf repo bundle
    - name: Publish Repository Bundle
      id: publish-repository-bundle
      uses: ./.github/actions/publish-bundle
      with:
        path: '${{ steps.build-repository-bundle.outputs.bundle-path }}'
        repository: ${{ inputs.repository-bundle }}
        version: ${{ inputs.package-version }}
        project-directory: '.'
