name: Fix Deployment Files

on:
  push:
    branches:
      - main

env:
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'liberica'

    - name: Build with Maven
      run: ./mvnw process-resources -P deploymentfiles

    - name: Check Deployment Files
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update k8s deployment files
        committer: SCDF Build Bot <scdf-build-bot@users.noreply.github.com>
        author: SCDF Build Bot <scdf-build-bot@users.noreply.github.com>
        body: |
          Detected a change with `mvn process-resources -P deploymentfiles`.

          This PR were created to align k8s deployment file changes.
        title: 'Update k8s deployment files'
        labels: automated pr
        assignees: ilayaperumalg
        reviewers: jvalkeal,ilayaperumalg
        branch: github-actions/update-deployment-files
